'use client';

import React, { useState, useEffect, useRef } from 'react';
import { useSearchParams } from 'next/navigation';
import {
  MessageType,
  MESSAGE_TYPE_LABELS,
  generateCancellationMessage,
} from '../templates';
import { Button } from '@/components/ui/button';
import { FieldLabel, FieldHint } from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Select } from '@/components/ui/select';
import { Card } from '@/components/ui/card';
import { InlineNotice } from '@/components/ui/inline-notice';
import { Link } from '@/i18n/navigation';
import { Copy, Check, RotateCcw, Calculator, Search, ArrowRight } from 'lucide-react';

export function CancellationMessageGenerator() {
  const searchParams = useSearchParams();
  const rawServiceParam = searchParams.get('service') || '';
  const initialService = rawServiceParam
    .replace(/[\u0000-\u001F\u007F-\u009F]/g, '')
    .trim()
    .slice(0, 100);

  const [name, setName] = useState('');
  const [serviceName, setServiceName] = useState(initialService);
  const [customerId, setCustomerId] = useState('');
  const [endDate, setEndDate] = useState('');
  const [messageType, setMessageType] = useState<MessageType>('standard');
  const [customNote, setCustomNote] = useState('');

  const [manualText, setManualText] = useState<string | null>(null);
  const [copyStatus, setCopyStatus] = useState<'idle' | 'copied' | 'manual'>('idle');
  const timerRef = useRef<NodeJS.Timeout | null>(null);

  useEffect(() => {
    return () => {
      if (timerRef.current) {
        clearTimeout(timerRef.current);
      }
    };
  }, []);

  // Compute text draft directly in-memory during render
  const autoGeneratedText = generateCancellationMessage({
    name,
    serviceName,
    customerId,
    endDate,
    customNote,
    messageType,
  });

  const currentText = manualText !== null ? manualText : autoGeneratedText;

  const handleCopy = async () => {
    if (timerRef.current) {
      clearTimeout(timerRef.current);
    }

    try {
      if (
        typeof navigator !== 'undefined' &&
        navigator.clipboard &&
        typeof navigator.clipboard.writeText === 'function'
      ) {
        await navigator.clipboard.writeText(currentText);
        setCopyStatus('copied');
      } else {
        const textarea = document.getElementById('generated-output') as HTMLTextAreaElement | null;
        if (textarea) {
          textarea.focus();
          textarea.select();
        }
        setCopyStatus('manual');
      }
    } catch {
      const textarea = document.getElementById('generated-output') as HTMLTextAreaElement | null;
      if (textarea) {
        textarea.focus();
        textarea.select();
      }
      setCopyStatus('manual');
    }

    timerRef.current = setTimeout(() => {
      setCopyStatus('idle');
    }, 4000);
  };

  const handleResetDraft = () => {
    setManualText(null);
  };

  const handleFormSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    // In-memory update; state already drives generation
  };

  const trimmedServiceName = serviceName.trim();
  const searchGuideUrl = trimmedServiceName
    ? `/sok?q=${encodeURIComponent(trimmedServiceName)}`
    : '/sok';

  return (
    <div className="flex flex-col gap-8">
      {/* Calm Neutral Privacy Boundary (Visible before entering personal info) */}
      <InlineNotice
        variant="information"
        title="Privacy Notice"
        aria-label="Privacy Notice"
      >
        What you type stays in your browser and is never sent to ByeScribe. Data is not saved when you leave the page.
      </InlineNotice>

      <Card variant="raised" as="section" aria-labelledby="form-heading" className="flex flex-col gap-8">
        <form onSubmit={handleFormSubmit} className="flex flex-col gap-8">
          {/* Group 1: Service Details */}
          <fieldset className="flex flex-col gap-4 border-0 p-0 m-0">
            <legend id="form-heading" className="text-base font-semibold text-[var(--color-text)] pb-2 border-b border-[var(--color-border)] w-full">
              1. Service Details
            </legend>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 sm:gap-6">
              {/* Service Name */}
              <div className="flex flex-col gap-1.5 sm:col-span-2">
                <FieldLabel htmlFor="msg-service" required>
                  Service name
                </FieldLabel>
                <Input
                  id="msg-service"
                  type="text"
                  maxLength={100}
                  autoComplete="off"
                  value={serviceName}
                  onChange={(e) => {
                    setServiceName(e.target.value);
                    setManualText(null);
                  }}
                  placeholder="e.g. Spotify or Netflix"
                />
              </div>

              {/* Message Type */}
              <div className="flex flex-col gap-1.5">
                <FieldLabel htmlFor="msg-type">
                  Type of message
                </FieldLabel>
                <Select
                  id="msg-type"
                  value={messageType}
                  onChange={(e) => {
                    setMessageType(e.target.value as MessageType);
                    setManualText(null);
                  }}
                >
                  {Object.entries(MESSAGE_TYPE_LABELS).map(([key, label]) => (
                    <option key={key} value={key}>
                      {label}
                    </option>
                  ))}
                </Select>
              </div>

              {/* Desired End Date */}
              <div className="flex flex-col gap-1.5">
                <FieldLabel htmlFor="msg-end-date">
                  Desired end date (optional)
                </FieldLabel>
                <Input
                  id="msg-end-date"
                  type="date"
                  value={endDate}
                  onChange={(e) => {
                    setEndDate(e.target.value);
                    setManualText(null);
                  }}
                />
                <FieldHint>
                  Leave blank to cancel as soon as possible.
                </FieldHint>
              </div>
            </div>
          </fieldset>

          {/* Group 2: Your Information */}
          <fieldset className="flex flex-col gap-4 border-0 p-0 m-0">
            <legend className="text-base font-semibold text-[var(--color-text)] pb-2 border-b border-[var(--color-border)] w-full">
              2. Your Information
            </legend>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 sm:gap-6">
              {/* User Name */}
              <div className="flex flex-col gap-1.5">
                <FieldLabel htmlFor="msg-name" required>
                  Your full name
                </FieldLabel>
                <Input
                  id="msg-name"
                  type="text"
                  maxLength={100}
                  autoComplete="off"
                  value={name}
                  onChange={(e) => {
                    setName(e.target.value);
                    setManualText(null);
                  }}
                  placeholder="First Last"
                />
              </div>

              {/* Customer / Membership ID */}
              <div className="flex flex-col gap-1.5">
                <FieldLabel htmlFor="msg-customer-id">
                  Customer or membership ID (optional)
                </FieldLabel>
                <Input
                  id="msg-customer-id"
                  type="text"
                  maxLength={100}
                  autoComplete="off"
                  value={customerId}
                  onChange={(e) => {
                    setCustomerId(e.target.value);
                    setManualText(null);
                  }}
                  placeholder="e.g. 123456 or email address"
                />
              </div>
            </div>
          </fieldset>

          {/* Group 3: Additional Details */}
          <fieldset className="flex flex-col gap-4 border-0 p-0 m-0">
            <legend className="text-base font-semibold text-[var(--color-text)] pb-2 border-b border-[var(--color-border)] w-full">
              3. Additional Details
            </legend>

            <div className="flex flex-col gap-1.5">
              <div className="flex items-center justify-between">
                <FieldLabel htmlFor="msg-note">
                  Additional notes or reason (optional)
                </FieldLabel>
                <FieldHint>
                  {customNote.length}/300
                </FieldHint>
              </div>
              <Textarea
                id="msg-note"
                maxLength={300}
                rows={2}
                autoComplete="off"
                value={customNote}
                onChange={(e) => {
                  setCustomNote(e.target.value);
                  setManualText(null);
                }}
                placeholder="e.g. relocating, changed contract terms, etc."
              />
            </div>
          </fieldset>

          <div className="flex items-center gap-3">
            <Button type="submit" variant="secondary" size="md">
              Update draft
            </Button>
          </div>
        </form>

        {/* Generated Output Area */}
        <section aria-labelledby="draft-heading" className="border-t border-[var(--color-border)] pt-8 flex flex-col gap-4">
          <div className="flex items-center justify-between flex-wrap gap-2">
            <h2 id="draft-heading" className="text-base font-normal text-[var(--color-text)]">
              Generated draft (editable)
            </h2>
            {manualText !== null && (
              <button
                type="button"
                onClick={handleResetDraft}
                className="inline-flex items-center gap-1.5 text-xs font-medium text-[var(--color-text-muted)] hover:text-[var(--color-text)] underline focus-visible:ring-2 focus-visible:ring-[var(--color-focus)] rounded-[var(--radius-sm)] outline-none py-1"
              >
                <RotateCcw className="w-3.5 h-3.5" aria-hidden="true" />
                <span>Reset to template</span>
              </button>
            )}
          </div>

          <div className="relative">
            <textarea
              id="generated-output"
              rows={12}
              value={currentText}
              onChange={(e) => {
                setManualText(e.target.value);
              }}
              aria-label="Generated cancellation message"
              className="w-full font-mono text-xs sm:text-sm p-4 bg-[var(--color-page)] text-[var(--color-text)] border border-[var(--color-border-strong)] hover:border-[var(--color-text-muted)] focus:border-[var(--color-text-muted)] rounded-[var(--radius-md)] focus:outline-none focus-visible:outline-none leading-relaxed transition-colors resize-y"
            />
          </div>

          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pt-1">
            <Button
              type="button"
              variant="primary"
              size="md"
              onClick={handleCopy}
              className="w-full sm:w-auto"
            >
              {copyStatus === 'copied' ? (
                <>
                  <Check className="w-4 h-4 text-[var(--color-positive)]" aria-hidden="true" />
                  <span>Copied to clipboard!</span>
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4" aria-hidden="true" />
                  <span>Copy message text</span>
                </>
              )}
            </Button>

            <div
              id="copy-status-live"
              aria-live="polite"
              className="text-xs text-[var(--color-text-muted)] flex-1 sm:text-right"
            >
              {copyStatus === 'copied' && (
                <span className="text-[var(--color-positive)] font-medium">
                  Text copied to clipboard. Paste it into your email client.
                </span>
              )}
              {copyStatus === 'manual' && (
                <span className="text-[var(--color-warning)] font-medium">
                  Select the text and copy manually (Ctrl+C / Cmd+C).
                </span>
              )}
              {copyStatus === 'idle' && (
                <span>The draft is not legally binding until you send it directly to the provider.</span>
              )}
            </div>
          </div>
        </section>
      </Card>

      {/* Next Steps Guidance */}
      <section aria-labelledby="msg-next-steps" className="border-t border-[var(--color-border)] pt-8 flex flex-col gap-4">
        <div className="flex flex-col gap-1">
          <h2 id="msg-next-steps" className="text-base font-normal text-[var(--color-text)]">
            Important instructions for sending
          </h2>
          <p className="text-sm text-[var(--color-text-muted)] leading-relaxed">
            ByeScribe does not send messages for you. You must send the text yourself via the provider&apos;s official channel (email, web form, or letter). Always save a copy of the sent message and the provider&apos;s written confirmation.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <Link
            href={searchGuideUrl}
            className="group p-5 bg-[var(--color-surface)] border border-[var(--color-border)] rounded-[var(--radius-card-visual)] hover:border-[var(--color-border-strong)] hover:shadow-subtle transition-all flex flex-col gap-2 focus-visible:ring-2 focus-visible:ring-[var(--color-focus)] outline-none text-left"
          >
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2.5">
                <div className="p-2 rounded-[var(--radius-md)] bg-[var(--color-page-subtle)] text-[#0284c7] dark:text-[#38bdf8]">
                  <Search className="w-4 h-4" aria-hidden="true" />
                </div>
                <span className="font-semibold text-sm text-[var(--color-text)] group-hover:text-[var(--color-accent)] transition-colors">
                  {trimmedServiceName ? `Search guide for ${trimmedServiceName}` : 'Find cancellation guide'}
                </span>
              </div>
              <ArrowRight className="w-4 h-4 text-[var(--color-text-subtle)] group-hover:text-[var(--color-accent)] group-hover:translate-x-1 transition-all" aria-hidden="true" />
            </div>
            <p className="text-xs text-[var(--color-text-muted)] leading-relaxed">
              Find official cancellation channels, contact details, and verified terms.
            </p>
          </Link>

          <Link
            href="/verktyg/besparingskalkylator"
            className="group p-5 bg-[var(--color-surface)] border border-[var(--color-border)] rounded-[var(--radius-card-visual)] hover:border-[var(--color-border-strong)] hover:shadow-subtle transition-all flex flex-col gap-2 focus-visible:ring-2 focus-visible:ring-[var(--color-focus)] outline-none text-left"
          >
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2.5">
                <div className="p-2 rounded-[var(--radius-md)] bg-[var(--color-page-subtle)] text-[#0d9488] dark:text-[#2dd4bf]">
                  <Calculator className="w-4 h-4" aria-hidden="true" />
                </div>
                <span className="font-semibold text-sm text-[var(--color-text)] group-hover:text-[var(--color-accent)] transition-colors">
                  Calculate savings
                </span>
              </div>
              <ArrowRight className="w-4 h-4 text-[var(--color-text-subtle)] group-hover:text-[var(--color-accent)] group-hover:translate-x-1 transition-all" aria-hidden="true" />
            </div>
            <p className="text-xs text-[var(--color-text-muted)] leading-relaxed">
              See how much you save over 1 year and 5 years by unsubscribing.
            </p>
          </Link>
        </div>
      </section>
    </div>
  );
}
