'use client';

import React, { useState } from 'react';
import { useSearchParams } from 'next/navigation';
import {
  MessageType,
  MESSAGE_TYPE_LABELS,
  generateCancellationMessage,
} from '../templates';
import { Button } from '@/components/ui/button';
import { FieldLabel, FieldHint } from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Select } from '@/components/ui/select';
import { Card } from '@/components/ui/card';
import { InlineNotice } from '@/components/ui/inline-notice';
import { BRAND } from '@/config/brand';
import { Copy, Check, RotateCcw } from 'lucide-react';

export function CancellationMessageGenerator() {
  const searchParams = useSearchParams();
  const initialService = (searchParams.get('service') || '')
    .replace(/[\u0000-\u001F\u007F-\u009F]/g, '')
    .trim()
    .slice(0, 100);

  const [name, setName] = useState('');
  const [serviceName, setServiceName] = useState(initialService);
  const [customerId, setCustomerId] = useState('');
  const [endDate, setEndDate] = useState('');
  const [messageType, setMessageType] = useState<MessageType>('standard');
  const [customNote, setCustomNote] = useState('');

  const [manualText, setManualText] = useState<string | null>(null);
  const [copyStatus, setCopyStatus] = useState<'idle' | 'copied' | 'error'>('idle');

  // Compute text draft directly during render
  const autoGeneratedText = generateCancellationMessage({
    name,
    serviceName,
    customerId,
    endDate,
    customNote,
    messageType,
  });

  const currentText = manualText !== null ? manualText : autoGeneratedText;

  const handleCopy = async () => {
    try {
      if (typeof navigator !== 'undefined' && navigator.clipboard && typeof navigator.clipboard.writeText === 'function') {
        await navigator.clipboard.writeText(currentText);
        setCopyStatus('copied');
      } else {
        const textarea = document.getElementById('generated-output') as HTMLTextAreaElement | null;
        if (textarea) {
          textarea.select();
          const success = document.execCommand('copy');
          if (success) {
            setCopyStatus('copied');
          } else {
            throw new Error('Fallback failed');
          }
        }
      }
      setCopyStatus('copied');
      setTimeout(() => setCopyStatus('idle'), 3000);
    } catch {
      setCopyStatus('error');
      setTimeout(() => setCopyStatus('idle'), 3000);
    }
  };

  const handleResetDraft = () => {
    setManualText(null);
  };

  return (
    <div className="flex flex-col gap-8">
      {/* Absolute Privacy Notice Banner */}
      <InlineNotice
        variant="information"
        title="🔒 Integritetsinformation"
        aria-label="Integritetsinformation"
      >
        Det du skriver stannar i din webbläsare och skickas inte till {BRAND.name}. All text genereras lokalt i minnet.
      </InlineNotice>

      <Card variant="raised" className="flex flex-col gap-6">
        <h2 className="text-base font-semibold text-[var(--color-text)]">
          1. Fyll i uppgifter för utkastet
        </h2>

        <form onSubmit={(e) => e.preventDefault()} className="grid grid-cols-1 sm:grid-cols-2 gap-4 sm:gap-6">
          {/* Service Name */}
          <div className="flex flex-col gap-1.5">
            <FieldLabel htmlFor="msg-service" required>
              Tjänstens namn
            </FieldLabel>
            <Input
              id="msg-service"
              type="text"
              maxLength={100}
              value={serviceName}
              onChange={(e) => {
                setServiceName(e.target.value);
                setManualText(null);
              }}
              placeholder="T.ex. Spotify eller Readly"
            />
          </div>

          {/* User Name */}
          <div className="flex flex-col gap-1.5">
            <FieldLabel htmlFor="msg-name" required>
              Ditt för- och efternamn
            </FieldLabel>
            <Input
              id="msg-name"
              type="text"
              maxLength={100}
              value={name}
              onChange={(e) => {
                setName(e.target.value);
                setManualText(null);
              }}
              placeholder="Förnamn Efternamn"
            />
          </div>

          {/* Customer / Membership ID */}
          <div className="flex flex-col gap-1.5">
            <FieldLabel htmlFor="msg-customer-id">
              Kundnummer eller medlemsnummer (valfritt)
            </FieldLabel>
            <Input
              id="msg-customer-id"
              type="text"
              maxLength={100}
              value={customerId}
              onChange={(e) => {
                setCustomerId(e.target.value);
                setManualText(null);
              }}
              placeholder="T.ex. 123456 eller e-postadress"
            />
          </div>

          {/* Desired End Date */}
          <div className="flex flex-col gap-1.5">
            <FieldLabel htmlFor="msg-end-date">
              Önskat avslutsdatum (valfritt)
            </FieldLabel>
            <Input
              id="msg-end-date"
              type="date"
              value={endDate}
              onChange={(e) => {
                setEndDate(e.target.value);
                setManualText(null);
              }}
            />
          </div>

          {/* Message Type */}
          <div className="flex flex-col gap-1.5 sm:col-span-2">
            <FieldLabel htmlFor="msg-type">
              Typ av meddelande
            </FieldLabel>
            <Select
              id="msg-type"
              value={messageType}
              onChange={(e) => {
                setMessageType(e.target.value as MessageType);
                setManualText(null);
              }}
            >
              {Object.entries(MESSAGE_TYPE_LABELS).map(([key, label]) => (
                <option key={key} value={key}>
                  {label}
                </option>
              ))}
            </Select>
          </div>

          {/* Custom Note */}
          <div className="flex flex-col gap-1.5 sm:col-span-2">
            <div className="flex items-center justify-between">
              <FieldLabel htmlFor="msg-note">
                Kompletterande information (valfritt)
              </FieldLabel>
              <FieldHint>
                {customNote.length}/300
              </FieldHint>
            </div>
            <Textarea
              id="msg-note"
              maxLength={300}
              rows={2}
              value={customNote}
              onChange={(e) => {
                setCustomNote(e.target.value);
                setManualText(null);
              }}
              placeholder="T.ex. flytt utomlands, ändrade villkor etc."
            />
          </div>
        </form>

        {/* Generated Output Area */}
        <div className="border-t border-[var(--color-border)] pt-6 flex flex-col gap-3">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-semibold text-[var(--color-text)]">
              2. Genererat utkast (redigerbart)
            </h3>
            {manualText !== null && (
              <button
                type="button"
                onClick={handleResetDraft}
                className="inline-flex items-center gap-1 text-xs text-[var(--color-text-muted)] hover:text-[var(--color-text)] underline cursor-pointer"
              >
                <RotateCcw className="w-3 h-3" aria-hidden="true" />
                <span>Återställ till mall</span>
              </button>
            )}
          </div>

          <div className="relative">
            <textarea
              id="generated-output"
              rows={12}
              value={currentText}
              onChange={(e) => {
                setManualText(e.target.value);
              }}
              aria-label="Genererat uppsägningsmeddelande"
              className="w-full font-mono text-xs sm:text-sm p-4 bg-[var(--color-page)] text-[var(--color-text)] border border-[var(--color-border-strong)] rounded-[var(--radius-md)] focus-visible:ring-2 focus-visible:ring-[var(--color-focus)] outline-none leading-relaxed transition-colors"
            />
          </div>

          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <Button
              type="button"
              variant="primary"
              size="md"
              onClick={handleCopy}
              className="w-full sm:w-auto"
            >
              {copyStatus === 'copied' ? (
                <>
                  <Check className="w-4 h-4 text-[var(--color-positive)]" aria-hidden="true" />
                  <span>✓ Kopierat till urklipp!</span>
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4" aria-hidden="true" />
                  <span>Kopiera meddelandetext</span>
                </>
              )}
            </Button>

            <div
              id="copy-status-live"
              aria-live="polite"
              className="text-xs text-[var(--color-text-muted)]"
            >
              {copyStatus === 'copied' && (
                <span className="text-[var(--color-positive)] font-medium">
                  Texten har kopierats. Klistra in den i ditt e-postprogram.
                </span>
              )}
              {copyStatus === 'error' && (
                <span className="text-[var(--color-critical)] font-medium">
                  Kunde inte kopiera automatiskt. Markera texten manuellt och tryck Ctrl+C / Cmd+C.
                </span>
              )}
              {copyStatus === 'idle' && (
                <span>Utkastet är inte juridiskt bindande förrän du själv skickar det.</span>
              )}
            </div>
          </div>
        </div>
      </Card>
    </div>
  );
}
